[17.0][FIX] edi_oca: error in component
OCA/edi-framework pull request #107
Opened 2024-08-29 06:23 UTC by manuelregidor

The component that shows the buttons on the top of the invoices form view is not properly migrated, which is the cause of an error that prevents the access to invoices. This fix sorts out the issue.

2024-08-29 06:27 UTC, manuelregidor commented
@ValentinVinagre Could you review, please?

2024-08-29 07:32 UTC, ValentinVinagre approved these changes
LGTM 👍🏻

2024-08-29 07:36 UTC, etobella commented
Where it was failing? Seeing the JS it shouldn't...

2024-08-29 07:49 UTC, ValentinVinagre commented
@manuelregidor Councillor, could you add some screenshots with the error given by the migration of the "l10n_es_facturae_face" module without this fix? 
Ty 😃

2024-08-29 11:30 UTC, manuelregidor commented
@etobella 

We have identified this issue when migrating the module l10n_es_facturae_face. When trying to access an invoice whose customer has the value "FACe" set in the field l10n_es_facturae_sending_code, a frontend error occurs.

![edi_oca_error_1](https://github.com/user-attachments/assets/87285e9a-ca54-4a55-880d-604a0dabc568)

Complete error:

```
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    Error: An error occured in the owl lifecycle (see this Error's "cause" property)
        at handleError (http://localhost:17069/web/assets/00a5a52/web.assets_web.min.js:916:101)
        at App.handleError (http://localhost:17069/web/assets/00a5a52/web.assets_web.min.js:1545:29)
        at Fiber._render (http://localhost:17069/web/assets/00a5a52/web.assets_web.min.js:941:19)
        at Fiber.render (http://localhost:17069/web/assets/00a5a52/web.assets_web.min.js:939:6)
        at ComponentNode.initiateRender (http://localhost:17069/web/assets/00a5a52/web.assets_web.min.js:1007:47)

Caused by: TypeError: Cannot read properties of undefined (reading 'name')
    at Field.template (eval at compile (http://localhost:17069/web/assets/00a5a52/web.assets_web.min.js:1503:374), <anonymous>:16:92)
    at Fiber._render (http://localhost:17069/web/assets/00a5a52/web.assets_web.min.js:940:96)
    at Fiber.render (http://localhost:17069/web/assets/00a5a52/web.assets_web.min.js:939:6)
    at ComponentNode.initiateRender (http://localhost:17069/web/assets/00a5a52/web.assets_web.min.js:1007:47)
```

This error is solved by the modifying the file /static/src/js/widget_edi.esm.js. The following lines

```
EdiConfigurationWidget.template = "edi_oca.EdiConfigurationWidget";

registry.category("fields").add("edi_configuration", EdiConfigurationWidget);
```

need to be replaced by

```
EdiConfigurationWidget.template = "edi_oca.EdiConfigurationWidget";

registry.category("fields").add("edi_configuration", {
    component: EdiConfigurationWidget,
});
```

It is not enough with those changes though, as another error occurs:

![edi_oca_error_2](https://github.com/user-attachments/assets/c7c59518-1cfd-4432-aa33-2e0135ec5478)

Detailed error:

```
OwlError: Invalid loop expression: "undefined" is not iterable
    Error: Invalid loop expression: "undefined" is not iterable
        at prepareList (http://localhost:17069/web/assets/83382b6/web.assets_web.min.js:1120:12)
        at EdiConfigurationWidget.template (eval at compile (http://localhost:17069/web/assets/83382b6/web.assets_web.min.js:1503:374), <anonymous>:14:54)
        at Fiber._render (http://localhost:17069/web/assets/83382b6/web.assets_web.min.js:940:96)
        at Fiber.render (http://localhost:17069/web/assets/83382b6/web.assets_web.min.js:939:6)
        at ComponentNode.initiateRender (http://localhost:17069/web/assets/83382b6/web.assets_web.min.js:1007:47)
```

It is because the component template is not properly defined. That is why the following function has been added to /static/src/js/widget_edi.esm.js file.

```
    getInfo() {
        return this.props.record.data.edi_config
    }
```
The way data is retrieved from the template is also modified. These lines

```
        <t t-foreach="props.value" t-as="rule_id" t-key="rule_index">
            <t t-set="rule" t-value="props.value[rule_id]" />
```

has been replaced by the following:

```
        <t t-foreach="this.getInfo()" t-as="rule_id" t-key="rule_index">
            <t t-set="rule" t-value="this.getInfo()[rule_id]" />
```

2024-09-02 09:16 UTC, ValentinVinagre commented
@peluko00 could u review? 
https://github.com/OCA/edi-framework/pull/91

2024-09-02 11:00 UTC, etobella requested changes

2024-09-02 11:00 UTC, etobella commented on edi_oca/static/src/js/widget_edi.esm.js
> +    getInfo() {
```suggestion
    get info() {
```

2024-09-02 11:00 UTC, etobella commented on edi_oca/static/src/js/widget_edi.esm.js
> +        return this.props.record.data.edi_config;
```suggestion
        return this.props.record.data[this.props.name];
```
This way it uses the field

2024-09-02 11:00 UTC, etobella commented on edi_oca/static/src/js/widget_edi.esm.js
> +
It is not necessary

2024-09-02 11:00 UTC, etobella commented on edi_oca/static/src/xml/widget_edi.xml
> +        <t t-foreach="this.getInfo()" t-as="rule_id" t-key="rule_index">
```suggestion
        <t t-foreach="info" t-as="rule_id" t-key="rule_index">
```

2024-09-02 11:00 UTC, etobella commented on edi_oca/static/src/xml/widget_edi.xml
> +            <t t-set="rule" t-value="this.getInfo()[rule_id]" />
```suggestion
            <t t-set="rule" t-value="info[rule_id]" />
```

2024-09-02 11:00 UTC, etobella commented on edi_oca/static/src/js/widget_edi.esm.js
> +    getInfo() {
if you want to have a getInfo, maybe it is better to have a get funcion, isn't it :wink:

2024-09-03 15:26 UTC, manuelregidor commented
@etobella Thanks for your feedback. Changes applied.

2024-09-03 15:29 UTC, etobella approved these changes
Thanks, it is cleaner now :smile:

2024-09-03 16:00 UTC, etobella commented
/ocabot merge patch

2024-09-03 16:04 UTC, merged