[18.0][MIG] edi_endpoint_oca
OCA/edi-framework pull request #130
Opened 2024-12-17 11:59 UTC by JordiMForgeFlow

2025-01-30 22:21 UTC, dnplkndll commented
@JordiMForgeFlow the dependancies on this get merged?

2025-01-31 07:25 UTC, JordiMForgeFlow commented
@dnplkndll the only missing is https://github.com/OCA/web-api/pull/78

2025-01-31 09:57 UTC, simahawk requested changes

2025-01-31 09:57 UTC, simahawk commented on edi_endpoint_oca/data/server_action.xml
> +records.filtered(lambda x: not x.registry_sync).write({"registry_sync": True})
Same remark as for https://github.com/OCA/web-api/pull/78 :wink:

2025-01-31 11:16 UTC, JordiMForgeFlow commented on edi_endpoint_oca/data/server_action.xml
> +records.filtered(lambda x: not x.registry_sync).write({"registry_sync": True})
@simahawk done! also included https://github.com/OCA/edi/pull/1110

2025-02-21 13:01 UTC, JordiBForgeFlow commented
@simahawk could you merge this one?

2025-03-14 08:22 UTC, JordiBForgeFlow commented
@simahawk @etobella can you merge this one?

2025-03-14 14:20 UTC, simahawk approved these changes

2025-03-14 14:20 UTC, simahawk commented
/ocabot migration edi_endpoint_oca
/ocabot merge nobump

2025-03-14 14:25 UTC, merged

2025-03-14 14:36 UTC, JordiBForgeFlow commented
Thanks!!

El vie, 14 mar 2025, 15:26, OCA Bot ***@***.***> escribió:

> Congratulations, your PR was merged at af49389
> <https://github.com/OCA/edi-framework/commit/af493899f6712e1f77724a59d4171172a5c79142>.
> Thanks a lot for contributing to OCA. ❤️
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/edi-framework/pull/130#issuecomment-2724869392>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB2T6VW7NE4UHRMZFBDUBXT2ULRHTAVCNFSM6AAAAABTYIHIYGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDOMRUHA3DSMZZGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
> [image: OCA-git-bot]*OCA-git-bot* left a comment (OCA/edi-framework#130)
> <https://github.com/OCA/edi-framework/pull/130#issuecomment-2724869392>
>
> Congratulations, your PR was merged at af49389
> <https://github.com/OCA/edi-framework/commit/af493899f6712e1f77724a59d4171172a5c79142>.
> Thanks a lot for contributing to OCA. ❤️
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OCA/edi-framework/pull/130#issuecomment-2724869392>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB2T6VW7NE4UHRMZFBDUBXT2ULRHTAVCNFSM6AAAAABTYIHIYGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDOMRUHA3DSMZZGI>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>