[16.0][ADD] edi_account_edifact_oca
OCA/edi-framework pull request #40
Opened 2023-11-08 04:23 UTC by QuocDuong1306

This module supports sending account invoices from EDI channels to the storage system.

Depend on:
- https://github.com/OCA/edi-framework/pull/39

2023-11-16 15:03 UTC, simahawk requested changes
Also see my comments on https://github.com/OCA/edi/pull/854

2023-11-16 15:03 UTC, simahawk commented on edi_account_edifact_oca/__manifest__.py
> +        "edi_storage_oca",
This module should not depend on storage. The framework is agnostic for this reason: it does not matter where you send to or receive files from.

2023-11-17 08:35 UTC, simahawk requested changes

2023-11-17 08:35 UTC, simahawk commented on edi_account_edifact_oca/components/listener.py
> +        edifact_backend = self.env.ref("edi_edifact_oca.edi_backend_type_edifact")
```suggestion
        backend_type = self.env.ref("edi_edifact_oca.edi_backend_type_edifact")
```

2023-11-17 08:35 UTC, simahawk commented on edi_account_edifact_oca/components/listener.py
> +            not move.partner_id
pls move this condition to a specific method. The direction is not needed (see the change that I proposed to the field name in the other PR).

2023-11-17 08:35 UTC, simahawk commented on edi_account_edifact_oca/demo/edi_exchange_type.xml
> +  send:
pls remove `send`

2023-12-11 08:43 UTC, QuocDuong1306 commented
Hi @simahawk , I updated

2024-02-01 16:15 UTC, simahawk requested changes

2024-02-01 16:15 UTC, simahawk commented on edi_account_edifact_oca/components/generate.py
> +            if exchange_record.model == "account.move" and exchange_record.res_id:
the model should be selected by `_apply_on` on the class

2024-02-01 16:15 UTC, simahawk commented on edi_account_edifact_oca/components/generate.py
> +        if exchange_record:
I think is impossible to not have an exchange record

2024-02-01 16:15 UTC, simahawk commented on edi_account_edifact_oca/components/generate.py
> +                move = self.env["account.move"].browse(exchange_record.res_id)
there's no need to browse. Use `self.record`.

2024-02-01 16:15 UTC, simahawk commented on edi_account_edifact_oca/components/generate.py
> +    _name = "edi.output.account.move.generate"
```suggestion
    _name = "edi.output.edifact.account.move.generate"
```

2024-02-01 16:15 UTC, simahawk commented on edi_account_edifact_oca/readme/USAGE.rst
> +* Config `Storage` of the EDI backend.
storage is not needed. Is not relevant how you send it.

2024-02-01 16:15 UTC, simahawk commented on edi_account_edifact_oca/tests/test_edi_account_edifact.py
> +        )
```suggestion
        exchange_record = self.invoice.exchange_record_ids[0]

2024-06-03 01:51 UTC, QuocDuong1306 commented
Thank @simahawk , the PR has been updated as suggested

2024-11-17 12:23 UTC, closed without merging