[16.0][MIG] edi_xml_oca: Migration to 16.0
OCA/edi-framework pull request #44
Opened 2023-11-30 08:39 UTC by QuocDuong1306

Moved from `edi/oca` and migrated to 16.0

2023-12-01 08:18 UTC, simahawk commented
[ON'T MERGE] test-requirements.txt](https://github.com/OCA/edi-framework/pull/44/commits/8271b225589c8e79ed814ff59e9219489afa1c3b) this is a normal test dep :wink:

2023-12-01 08:22 UTC, simahawk reviewed
LG but the test req commit

2023-12-01 09:12 UTC, QuocDuong1306 commented
I updated

2023-12-15 09:17 UTC, simahawk requested changes

2023-12-15 09:17 UTC, simahawk commented on edi_xml_oca/__manifest__.py
> +    "external_dependencies": {"python": ["xmlschema", "xmlunittest"]},
this should go only to tests-requirements

2023-12-15 09:17 UTC, simahawk commented on requirements.txt
> +xmlunittest
not here, tests-req

2023-12-18 07:52 UTC, simahawk approved these changes

2023-12-18 07:53 UTC, simahawk commented
/ocabot merge nobump

2023-12-18 07:58 UTC, merged