[IMP] edi_oca: Allow to use a sequence as part of exchange filename pattern
OCA/edi-framework pull request #57
Opened 2024-01-16 10:59 UTC by tuantrantg

2024-01-19 06:24 UTC, simahawk requested changes
`[IMP] edi_oca: allow use of sequence for exchange filename pattern`

2024-01-19 06:24 UTC, simahawk commented on edi_oca/models/edi_exchange_type.py
> +        default="{record_name}-{type.code}-{dt}-{seq}"
IMO It shouldn't be here by default. However, we should have a help text to explain all avail variables.

2024-01-19 06:24 UTC, simahawk commented on edi_oca/models/edi_exchange_type.py
> +        "ir.sequence", "Exchange Filename Sequence"
help txt pls

2024-01-19 06:24 UTC, simahawk commented on edi_oca/models/edi_exchange_type.py
> +            or ""
```suggestion
            self.exchange_filename_sequence_id.next_by_id()
            if self.exchange_filename_sequence_id
            else ""
```

2024-01-19 06:24 UTC, simahawk commented on edi_oca/models/edi_exchange_type.py
> +        seq = self._make_exchange_filename_sequence()
this requires a test

2024-01-19 09:45 UTC, tuantrantg commented
hi @simahawk please review this PR again, thank you

2024-01-22 08:04 UTC, simahawk approved these changes

2024-01-23 11:25 UTC, simahawk commented
/ocabot merge minor

2024-01-23 11:30 UTC, merged