[16.0][MIG] edi_endpoint_oca
OCA/edi-framework pull request #7
Opened 2023-06-09 12:50 UTC by JordiBForgeFlow

Standard migration.

Todo:
* [ ] Functional review
* [ ] Review automated tests

2023-10-02 14:15 UTC, simahawk requested changes

2023-10-02 14:15 UTC, simahawk commented on edi_endpoint_oca/models/__init__.py
> -from . import edi_exchange_consumer_mixin
WHY?

2023-10-04 08:14 UTC, LoisRForgeFlow commented
rebased

2023-12-18 08:46 UTC, thienvh332 commented
LGTM
@JordiBForgeFlow Pre-commit is not happy. Could you please take a look.

2024-01-31 16:49 UTC, simahawk commented
@JordiBForgeFlow @LoisRForgeFlow could you please have a look at #46 ?

2024-01-31 16:49 UTC, closed without merging