[16.0][ADD] edi_notification_oca
OCA/edi-framework pull request #78
Opened 2024-03-27 01:53 UTC by QuocDuong1306

2024-03-27 08:09 UTC, simahawk requested changes

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/models/edi_exchange_type.py
> +    send_notification_on_error = fields.Boolean(
```suggestion
    notify_on_process_error = fields.Boolean(
```
this is just for `process` action

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/models/edi_exchange_type.py
> +            if not rec.send_notification_on_error:
I'm not sure this constraint is useful. The other fields should be hidden when the flag is off and you already have the onchange to wipe the fields.

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/readme/CONTRIBUTORS.rst
> +* Duong (Tran Quoc) <duontq@troz.com>
```suggestion
* Duong (Tran Quoc) <duontq@troz.com>
* Simone Orsi <simone.orsi@camptocamp.com>
```

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/tests/test_edi_notification.py
> +        return self.env["res.users"].create(
```suggestion
        return self.env["res.users"].with_context(no_reset_password=True).create(
```
Always :wink: 
Or... use `new_test_user` from `odoo.tests.common`.

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/models/edi_exchange_type.py
> +    notification_groups_ids = fields.Many2many(
```suggestion
    notify_on_process_error_groups_ids = fields.Many2many(
```

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/models/edi_exchange_type.py
> +    notification_users_ids = fields.Many2many(
```suggestion
    notify_on_process_error_users_ids = fields.Many2many(
```

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/models/edi_exchange_type.py
> +        comodel_name="res.groups", string="Notification Groups"
```suggestion
        comodel_name="res.groups", string="Notify groups on process error"
```

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/models/edi_exchange_type.py
> +        string="Notification Users",
```suggestion
        string="Notify users on process error",
```

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/components/listener.py
> +                "edi_notification_oca.mail_activity_failed_exchange_record_warning",
I would make the activity configurable on the type too w/ default to this one if available.

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/components/listener.py
> +                user_id=user.id,
```suggestion
                user_id=user.id,
                automated=True
```

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/components/listener.py
> +            users |= exc_type.notification_users_ids
```suggestion
        users = self._get_users_to_notify(record, exc_type)
```

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/components/listener.py
> +                summary=_("Error on process of record '%s'.", record.identifier),
```suggestion
                summary=_("EDI: process error on record '%(identifier)s'.", identifier=record.identifier),
```

2024-03-27 08:09 UTC, simahawk commented on edi_notification_oca/tests/test_edi_notification.py
> +        b_noti = self.env["mail.activity"].search(
I'd recommend using `RecordCapturer` from `odoo.tests.common` :wink:

2024-03-27 09:30 UTC, QuocDuong1306 commented on edi_notification_oca/models/edi_exchange_type.py
> +            if not rec.send_notification_on_error:
Hello @simahawk , i think we  can handle some cases: we write through code with groups and users but forgot to enable  `notify_on_process_error`, the `onchange` didn't work with case...

2024-03-27 10:42 UTC, simahawk commented on edi_notification_oca/models/edi_exchange_type.py
> +            if not rec.send_notification_on_error:
then maybe better to use an inverse?

2024-03-27 14:58 UTC, QuocDuong1306 commented
Thank @simahawk , I updated

2024-04-04 07:15 UTC, simahawk requested changes

2024-04-04 07:15 UTC, simahawk commented on edi_notification_oca/models/edi_exchange_type.py
> +        default=_default_notify_on_process_error_activity_type_id,
Rule of thumb: always avoid referencing methods' objects. Use lambdas to proxy the call
```suggestion
        default=lambda self: self._default_notify_on_process_error_activity_type_id(),
```
and keep the default method after the fields def

2024-04-04 07:15 UTC, simahawk commented on edi_notification_oca/tests/test_edi_notification.py
> +        cls.group_sale = cls.env.ref("sales_team.group_sale_salesman")
this implies a dependency on sales_team that is not necessary

2024-04-04 08:10 UTC, QuocDuong1306 commented
Thank @simahawk , I updated

2024-04-16 06:18 UTC, cyrilmanuel commented
@simahawk is it ok for you ?

2024-07-22 11:40 UTC, simahawk reviewed
@QuocDuong1306 just 2 minor remarks. The rest LG, thanks!

2024-07-22 11:40 UTC, simahawk commented on edi_notification_oca/__manifest__.py
> +    "summary": """Define Notification Activities When Exchange Record.""",
when exchange record.... what?

2024-07-22 11:40 UTC, simahawk commented on edi_notification_oca/components/listener.py
> +        return users
```suggestion
        return exc_type.notify_on_process_error_groups_ids.users | exc_type.notify_on_process_error_users_ids
```

2024-07-22 11:41 UTC, simahawk commented on edi_notification_oca/__manifest__.py
> +    "name": "EDI Notification OCA",
```suggestion
    "name": "EDI Notification",
```

2024-07-25 06:36 UTC, simahawk approved these changes

2024-07-25 06:37 UTC, simahawk commented
/ocabot merge nobump

2024-07-25 06:42 UTC, merged