[IMP] edi_oca: Improve archive/unarchive exchange type rules
OCA/edi-framework pull request #79
Opened 2024-04-01 05:20 UTC by QuocDuong1306

Change of behavior:
  - When an exchange type is archived, its exchange type rules are also archived (same as before)
  - When an exchange type is re-activated, its exchange type rules are also re-activated (new)

2024-04-01 07:48 UTC, etobella commented
I don't like both of the approaches... If we do it this way, if I inactivate a rule and then I inactivate and activate the type, the rule will be active again... why don't we keep it separated and improve the search of rules by checking that the rule and the type is active?

2024-04-02 05:34 UTC, santostelmo approved these changes

2024-04-03 07:02 UTC, simahawk requested changes
> I don't like both of the approaches... If we do it this way, if I inactivate a rule and then I inactivate and activate the type, the rule will be active again... 

I agree

> why don't we keep it separated and improve the search of rules by checking that the rule and the type is active?

The rules are already searched and the active flag should play is role (unless you enforce active_test) in the ctx -> we could enforce this in the domain maybe.

2024-04-04 03:40 UTC, QuocDuong1306 commented
Thanks for your suggestion, I think this improvement is not needed, so I close

2024-04-04 03:40 UTC, closed without merging